# Generated by Django 4.2.6 on 2023-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(null=True)),
                ('registration_date', models.IntegerField(null=True)),
                ('application_number', models.IntegerField(null=True)),
                ('application_date', models.IntegerField(null=True)),
                ('authors', models.CharField(max_length=255, null=True)),
                ('authors_count', models.IntegerField(null=True)),
                ('right_holders', models.CharField(max_length=255, null=True)),
                ('contact_to_third_parties', models.CharField(max_length=255, null=True)),
                ('program_name', models.CharField(max_length=255, null=True)),
                ('creation_year', models.IntegerField(null=True)),
                ('registration_publish_date', models.IntegerField(null=True)),
                ('registration_publish_number', models.IntegerField(null=True)),
                ('actual', models.BooleanField(null=True)),
                ('publication_url', models.URLField(null=True)),
            ],
            options={
                'get_latest_by': 'registration_date',
            },
        ),
    ]
