# Generated by Django 4.2.6 on 2023-10-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='authors_count',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='contact_to_third_parties',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='creation_year',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='registration_publish_date',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='registration_publish_number',
        ),
    ]
