# Generated by Django 4.2.6 on 2023-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patent_authors_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(null=True)),
                ('registration_date', models.IntegerField(null=True)),
                ('application_number', models.IntegerField(null=True)),
                ('application_date', models.IntegerField(null=True)),
                ('authors', models.CharField(max_length=255, null=True)),
                ('right_holders', models.CharField(max_length=255, null=True)),
                ('actual', models.BooleanField(null=True)),
                ('publication_url', models.URLField(null=True)),
                ('table', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'registration_date',
            },
        ),
        migrations.DeleteModel(
            name='Patent',
        ),
    ]
