# Generated by Django 4.2.6 on 2023-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entitys_delete_entity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entitys',
            new_name='Entity',
        ),
    ]
