# Generated by Django 4.2.6 on 2023-10-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_entitys_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='right_holders',
        ),
    ]
