# Generated by Django 4.2.6 on 2023-10-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_entity_right_holders'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.FloatField(null=True)),
                ('registration_date', models.IntegerField(null=True)),
                ('application_number', models.IntegerField(null=True)),
                ('application_date', models.IntegerField(null=True)),
                ('actual', models.BooleanField(null=True)),
                ('publication_url', models.URLField(null=True)),
            ],
            options={
                'get_latest_by': 'registration_date',
            },
        ),
    ]
