# Generated by Django 4.2.6 on 2023-10-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_entity_registration_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsefulModel',
        ),
    ]
