# Generated by Django 4.2.6 on 2023-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_usefulmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='registration_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
