# Generated by Django 4.2.6 on 2023-10-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_entity_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='table',
            new_name='database',
        ),
    ]
