# Generated by Django 4.2.6 on 2023-10-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_table_entity_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='database',
            new_name='table',
        ),
    ]
